# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  combobulate = {
    pname = "combobulate";
    version = "0a0907ce6696c97508eae71874ce69611e113ad0";
    src = fetchgit {
      url = "https://github.com/mickeynp/combobulate.git";
      rev = "0a0907ce6696c97508eae71874ce69611e113ad0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-GK21d/fbYe+LvMdyYpPHRKeBTSo7QzMvsCWlcG0lAao=";
    };
    date = "2023-05-17";
  };
  eshell-p10k = {
    pname = "eshell-p10k";
    version = "402bd88bb4a187c35cc3f2bb98551f850476f3b3";
    src = fetchgit {
      url = "https://github.com/elken/eshell-p10k";
      rev = "402bd88bb4a187c35cc3f2bb98551f850476f3b3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-fqv2lcBnNeDZhwFueLp//azGy6shTw73lMbYmvkErrg=";
    };
    date = "2021-11-08";
  };
  eshell-vterm = {
    pname = "eshell-vterm";
    version = "e96c30ad5e7d63b778fc3232e81b090b63b13277";
    src = fetchgit {
      url = "https://github.com/iostapyshyn/eshell-vterm";
      rev = "e96c30ad5e7d63b778fc3232e81b090b63b13277";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-fjPPTKlLYoyen9rhBs3F/fm5fvZ2YUYI65SrgrYX7n0=";
    };
    date = "2022-12-29";
  };
  jsonian = {
    pname = "jsonian";
    version = "e6a6a8452fc84f77bf5644851306c8b8d63a3bc5";
    src = fetchgit {
      url = "https://github.com/iwahbe/jsonian";
      rev = "e6a6a8452fc84f77bf5644851306c8b8d63a3bc5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dx+wJf/qZgMqR2SsyATB3u0NDiKLgBkDmbS7+C5jyKs=";
    };
    date = "2023-04-14";
  };
}
